version: "3"

env:
  TEMPL_DIR: Asp.AwesomeTemplates.Spa

dotenv: [".env.prod"]

tasks:
  remove:
    dir: '{{.TEMPL_DIR}}\nupkg\'
    cmds:
      - pwd
      - dotnet new --uninstall $TEMPL_NAME
      - rm -rf *
    ignore_error: true

  create:
    dir: "{{.TEMPL_DIR}}"
    cmds:
      - dotnet pack
    ignore_error: true

  create/release:
    dir: "{{.TEMPL_DIR}}"
    cmds:
      - dotnet pack
    ignore_error: true

  install:
    dir: '{{.TEMPL_DIR}}\nupkg\'
    cmds:
      - dotnet new --install $NUGET_FILE
    silent: false

  new:
    dir: '{{.TEMPL_DIR}}\nupkg\'
    cmds:
      - dotnet new $TEMPL_DOTNET_NAME -o $TEST_PROJ_NAME

  run-dotnet:
    dir: '{{.TEMPL_DIR}}\nupkg\{{.TEST_PROJ_NAME}}'
    cmds:
      - dotnet run

  run:
    dir: '{{.TEMPL_DIR}}\nupkg\{{.TEST_PROJ_NAME}}\{{.TEST_PROJ_NAME}}'
    cmds:
      - docker compose up

  all:
    cmds:
      - task: remove
      - task: create
      - task: install
      - task: new

  list:
    cmds:
      - dotnet new -l

  info:
    cmds:
      - dotnet new $TEMPL_DOTNET_NAME -h

  deploy:
    dir: '{{.TEMPL_DIR}}\nupkg'
    deps: [remove]
    cmds:
      - task: create/release
      - dotnet nuget push $NUGET_FILE --api-key $NUGET_APIKEY --source https://api.nuget.org/v3/index.json
